### ISSUE TITLE
Bug: bypass maintenance without role with 404 error.

### ISSUE THREAD

**Issue by odie2** [Codeinwp/wp-maintenance-mode#100]
Hello,

I tried to take fast look on mobile website, just migrated from localhost and did typo:

http://zschocianow.nazwa.pl/wordpress/wp-login
(Currently I have no phpmyadmin access, so due no images - some display bugs.)

And for my surprise, I have got 404 page with no signed in and editor role needed to see front- and back- end.

In my opinion, each possibility to access site - when maintenance mode and no needed privileges - should be dismissed.

Greetings

**Comment by wariotx** [comment]
I agree.

Is this going to be fixed anytime soon?
