### ISSUE TITLE
Change 'Contact Us' button colour

### ISSUE THREAD

**Issue by yoyosamo** [Codeinwp/wp-maintenance-mode#109]
Hello Designmodocom,

This plugin is almost _perfect_ for my site, however, I am using a mainly white background image.
Could you please tell me how to (or even add a feature to) either:
- Choose any colour for the Contact Us button, or
- Choose between the white or black buttons?

Many thanks,
~ Yoyosamo :)

**Comment by sebwag** [comment]
I support this request.

**Comment by sebwag** [comment]
This was fast 😂
