### ISSUE TITLE
Unable to properly localize

### ISSUE THREAD

**Issue by mobby2561** [Codeinwp/wp-maintenance-mode#140]
Hi,

I'm unable to properly localize your plugin. You don't stick the [basics of pluralization](https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#plurals).

In some languages it looks really ugly.

**Comment by Mahjouba91** [comment]
Hey, can you provide strings that are not well translated for pluralization please ?

**Comment by mobby2561** [comment]
Hi, here it is
[https://translate.wordpress.org/projects/wp-plugins/wp-maintenance-mode/stable/cs/default?filters[status]=either&filters[original_id]=645030&filters[translation_id]=44573330](url)

Previously i thought that days, hours and munutes are also visible in frontend. 
Sorry, my bad.

**Comment by mobby2561** [comment]
BTW the anouncement about codepad can't be translated.
