### ISSUE TITLE
how to add Piwik open-source analytics code ?

### ISSUE THREAD

**Issue by raykai** [Codeinwp/wp-maintenance-mode#159]
Hi,

just wondering if there is a way i could add a [Piwik ](https://piwik.org/) analytics code? i know you support google analytics .. but Piwik is open-source.

The code i need to add looks like this:
```
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//domain.com/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
```

but if i add it to the Text box in the Design tab it will remove the javascript ones i save it.

**Comment by georgejipa** [comment]
Hello @raykai,

You can add the code programatically. Example:

```php
// place the code into functions.php of your theme / child theme
function wpmm_add_piwik() {
?>
<!-- Piwik -->
<script type="text/javascript">
  var _paq = _paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//domain.com/piwik/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Piwik Code -->
<?php
}
add_action( 'wpmm_head', 'wpmm_add_piwik' );
```

**Comment by raykai** [comment]
i have the WP piwik plugin it adds the code to all the WP pages and has many options ... but the only time its not showing the code is when i turn on your plugin maintenance on... is there a place in your addon file that i can add this code?

**Comment by georgejipa** [comment]
Hello @raykai,

As I already said, [this](https://github.com/Designmodocom/WP-Maintenance-Mode/issues/159#issuecomment-310980210) is the only way to add the code.

Thanks.

**Comment by raykai** [comment]
this is the WP plugin for Piwik:
https://wordpress.org/plugins/wp-piwik/
as seen here too : https://piwik.org/blog/2015/05/wordpress-integration-wp-piwik-1-0/
