### ISSUE TITLE
Custom social media icons and high DPI support

### ISSUE THREAD

**Issue by realies** [Codeinwp/wp-maintenance-mode#162]
It would be great if there's an option for adding custom icons, being able to position them in a footer and adding retina support as icons look blurry on displays with higher pixel density.

Edit: Looking into it further, it seems that all sprite icons can be replaced by something vector and more modern such as FontAwesome.

**Comment by georgejipa** [comment]
Hello @realies,

This improvement is already on our to-do list. So... the social media icons will replaced with FontAwesome in a future version of the plugin. ;)

Thanks.
