### ISSUE TITLE
Infinite Redirects After Upgrading to 2.1.2

### ISSUE THREAD

**Issue by kesed** [Codeinwp/wp-maintenance-mode#177]
We have WP Maintenance Mode 2.1.2 installed on WordPress 4.9.4. We're using Pantheon as the hosting provider and have Cloudflare in front of that. The site is HTTPS. 

Maintenance mode was working properly up to version 2.0.9 but we recently updated to the latest version, 2.1.2, and now we receive the `ERR_TOO_MANY_REDIRECTS` message when trying to load the site as a logged out user when maintenance mode is turned on. Oddly enough, this is actually the reason we have been using your plugin - most other maintenance mode plugins have the infinite redirect issue and we were happy that yours did not (until this latest version).

Please let us know how we can help troubleshoot this issue so that hopefully a fix can be applied and we can continue using the plugin.

**Comment by sturtus** [comment]
Same.

**Comment by zreedeecom** [comment]
Still happening with latest release?
