### ISSUE TITLE
Plugin not doing what it should - maybe because of network installation or because of WP 6.0?

### ISSUE THREAD

**Issue by haraldballuch** [Codeinwp/wp-maintenance-mode#283]
I have 4 sites in my WP instance. 1 of them was already in maintenance mode and everything worked so far. (At least I didn't see any bugs.) Now a second one should be in maintenance mode, but that doesn't work. There is normal access to the frontend. The only url that seems to be blocked is "feed" because I removed it from the excludes. On the other hand in the site, that was already in maintenance mode "feed" is not blocked although I removed it from the exclude list.
I am using WP 6.0.
Strange is also that I see the rollback link of the plugin only in the plugin list of each site, but not in the plugin list in the network administration.

**Comment by haraldballuch** [comment]
I do not know what happened but now the second site is successfully in maintenance mode. The only issue that is left, is that "feed" of the first site is still not blocked, although it is removed from the exceptions. Is it possible that this is some caching issue?

**Comment by selul** [comment]
hi @haraldballuch, 

In order to help us isolate the issue, can you confirm if using a pre-6.0 version is fixing this?

**Comment by haraldballuch** [comment]
Today morning the feed of the first site was also in maintenance mode. So everything was ok. To test it I put "feed" in the exclude list again. It was immediately unblocked. When I removed it from the list again, it stayed unblocked. But from the last experience I would guess, that it will be blocked within the next few hours.
I am afraid, that I won't be able to invest enough time in the next days, so test it more intense and to rollback WP to 5.9. Right now I am relieved, that it works again, although configuration changes seem to take a lot of time to come into effect.

**Comment by selul** [comment]
thanks @haraldballuch, will close this for now, feel free to re-open if you need further help.
