### ISSUE TITLE
IP addresses added to the exclusion list don't work

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/wp-maintenance-mode#284]
In the general section of the plugin, it's possible to add IP addresses that you want to exclude from maintenance mode (to allow accessing the website:
<img width="951" alt="image" src="https://user-images.githubusercontent.com/36594177/171064969-4e2ea71c-7984-43f9-be45-3460e019ac87.png">

However, this doesn't work and IP addresses added here still can't access the website.
Reported here: https://wordpress.org/support/topic/whitelisting-ip-address-not-working/

I've added a custom code as a workaround in the thread also.

**Comment by girishpanchal30** [comment]
@vytisbulkevicius
I have tested it on my and its working correctly. IP address excluded for me using public IP as well as proxy IP. for details refer below video link. Also can you please share how to replicate this issue step?

https://www.awesomescreenshot.com/video/9257106?key=c181a33333abc349496f42cf77aba2c2

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

I've checked your video and you're doing everything just like I tried. I also tested now on a different server (created with https://app.instawp.io/dashboard) and it works fine as it works for you.

I was testing on tastewp instance before - https://tastewp.com/dashboard#! and tried again today - there it doesn't work.
Based on how we set the exclusion, could it be related to the server architecture and web server?
I will ask that user to provide Site Health info also so we can check as in TasteWp there is very specific information to their service:
https://vertis.d.pr/B1bEi6

**Comment by girishpanchal30** [comment]
@vytisbulkevicius 
need to check it on different server for that instead of TasteWp Instance because it will take sometime to activate maintenance mode so.

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

It works fine for me on other servers tested, the issue is only with TasteWP instances - https://tastewp.com

User hasn't replied about his server specifications and other uses haven't reported such an issue.
