### ISSUE TITLE
Enable/disable maintenance mode for sub-sites from one place

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/wp-maintenance-mode#295]
Could we add an option to enable/disable the maintenance mode for subsites from one place instead of accessing and modifying each subsite?

Suggested [here](https://wordpress.org/support/topic/images-still-accessible-and-multi-site/).

**Comment by bderaguts** [comment]
Would also be great to include this within the plugin: https://github.com/aaroneaton/Multisite-Maintenance-Mode

This old plugin keeps the site live, but blocks non-super admins from logging in to their admin during maintenance.

**Comment by girishpanchal30** [comment]
Hey @MarinescuLucia
I have added network/main site support so now users can config plugin settings for all subsites.
Ref: https://www.awesomescreenshot.com/image/30117298?key=d448b405cffe32fc7664ae2d4f3c1780

Also, users can use the individual setting option if maintenance mode is activated otherwise setting option overrides from network/main site.

Related #285

cc @selul

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested the feature and here is what i found:

If i have a network with the main site (https://multisite.s.themeisle.com/) and 2 other subsites (https://multisite.s.themeisle.com/second , https://multisite.s.themeisle.com/third), activating the maintenance mode in the **main site's dashboard** will also activate it on the **network dashboard**, and therefore in frontend the mode will be enabled on all subsites. The changes should be reflected on the whole network only when they are setted in the network dashboard. 

You can check it here:
```
URL : https://multisite.s.themeisle.com/
Username : multisite
Password : zHwUoI26
```

**Comment by girishpanchal30** [comment]
Hi @irinelenache,
I have fixed above mentioned issue please check and do let me know if you have any issues.

Thanks

**Comment by girishpanchal30** [comment]
@irinelenache Fixed, Can do a retest with the latest commit?

**Comment by girishpanchal30** [comment]
> @girishpanchal30 Tested again, now if i have the mode deactivated on every site and want to activate it in the network dashboard, i'll get some error in the frontend for every site https://vertis.d.pr/1ygujL

@irinelenache Fixed all PHP notices, Please check with the latest commit.
