### ISSUE TITLE
Accessibility issues on the maintenance page

### ISSUE THREAD

**Issue by SophieWeb** [Codeinwp/wp-maintenance-mode#296]
When using this plugin, the maintenance page in its simple version has three issues:  

- zooming is blocked through the `<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />` property :` user-scalable-no` should be removed, `maximum-scale` should be either removed or set to 2.0 for example
- no language is set on the page. It should use the site’s language attributes
- the page has no landmark. It can be fixed either by addind a `<main>` wrapper or adding `role="main"` to the `<div class="wrap">`

**Comment by selul** [comment]
Thanks @SophieWeb for your contribution, we will review this.
