### ISSUE TITLE
Automatically disable the maintenance mode when the countdown is finished

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/wp-maintenance-mode#300]
A user suggested that it would be a nice touch if the maintenance mode could be automatically disabled when the countdown from the Modules tab is finished.

Suggested [here](https://wordpress.org/support/topic/go-online-automatically/#post-15834241).

**Comment by stefan-cotitosu** [comment]
+1 https://secure.helpscout.net/conversation/2283874390/374506/

**Comment by stefan-cotitosu** [comment]
@girishpanchal30, can you please help me to confirm, is this in production?

So is it supposed that the maintenance mode is turned off when the counter finishes? I tested it and it doesn't work, the site remains in maintenance mode after the countdown ends. Maybe I missed a setting.

**Comment by girishpanchal30** [comment]
Hey @stefan-cotitosu,
The attached PR is not merged into the development or master. It seems the latest plugin is not working with the attached PR.
Thanks
