### ISSUE TITLE
Bot not registering subscribers

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/wp-maintenance-mode#302]
When the Bot is activated, users that add their email in order to subscribe don't appear in the Modules -> Subscribe -> Stats field. That number remains 0 even if the user subscribed through the messages received from the bot.

After the user adds the email, there is a security popup that appears, I'm not sure if it may be related to this issue.

![Capture](https://user-images.githubusercontent.com/86592341/182595048-ab14b6c4-f188-4589-b9a5-c4e2f82469ed.PNG)

Reported [here](https://wordpress.org/support/topic/bot-working-but-does-not-register-subscribers/#post-15884272).

**Comment by leonardolinoss** [comment]
Good afternoon.
I'm Leonardo, from the interior of the State of Pernambuco, Brazil.
I'm having the same problem when I use boot. When I disable the boot and let the countdown, the email subscription works normally. I would really appreciate it if someone could see what's wrong, as I followed all the procedures in these posts that deal with the same subject, but the boot inscription doesn't work, causing this screen security message. Thank you very much. Anyone who wants access, please get in touch
![Imagem1](https://user-images.githubusercontent.com/68669458/183301678-e9c99f56-944b-4228-8ff5-ea5b34593556.png)
.

**Comment by girishpanchal30** [comment]
Hello @leonardolinoss,

This issue is resolved in this PR https://github.com/Codeinwp/wp-maintenance-mode/pull/304, Please download the plugin from PR and test it.
will release the latest plugin asap.

Thanks
