### ISSUE TITLE
Shortcode: Embed not working

### ISSUE THREAD

**Issue by IlluminatePro** [Codeinwp/wp-maintenance-mode#308]
WP: 6.0.1
Version 2.4.7

Instructions say "[embed] - responsive video embed. Compatible with YouTube, Vimeo, DailyMotion. Example: [embed]https://www.youtube.com/watch?v=HCfPhZQz2CE[/embed]" 

ISSUE: When I embed the example or my own URL [embed]https://www.vimeo.com/739328714[/embed], video does not display on the maintenance page, see https://ngcnetworkstv.com

Note: 
Bot feature is disabled as noted in instructions 
Vimeo video is public. 

Plug-Ins: 
Akismet Anti-Spam (deactivated)
All-In-One WP Migration (deactivated)
Hosting (deactivated)
WP-Maintenance Mode & Coming Soon (Active)

[Embed-Bug1.pdf](https://github.com/Codeinwp/wp-maintenance-mode/files/9385992/Embed-Bug1.pdf)
[Embed-Bug2.pdf](https://github.com/Codeinwp/wp-maintenance-mode/files/9385994/Embed-Bug2.pdf)

**Comment by girishpanchal30** [comment]
Hello @IlluminatePro,
I have tested it with my local and it working fine for me. Can you please create a WP test instance( tastewp.com ) and share details here?
Ref: https://tinyurl.com/2kpehkzs

@irinelenache Can you please test this issue with provided details?

Thanks

**Comment by IlluminatePro** [comment]
Thank you for your quick response. 
Can be seen here https:.//ngcnetworktv.com
@irinelenache what additional details can I provide? Thank you for your help.

**Comment by girishpanchal30** [comment]
Hello @IlluminatePro,

I have found the issue and it's fixed now. you can see the changes in the next plugin release.

As of now, you need to add the below filter in the active theme functions.php file.

```
add_filter(
	'wp_kses_allowed_html',
	function( $allowed_html = array() ) {
		return array(
			'iframe' => array(
				'src'             => array(),
				'height'          => array(),
				'width'           => array(),
				'frameborder'     => array(),
				'allowfullscreen' => array(),
				'data-*'          => true,
			),
		);
	}
);
```

Thanks

**Comment by IlluminatePro** [comment]
Many thanks for the functions.php temp fix and I'll watch for the next release.  Cheers!

**Comment by IlluminatePro** [comment]
Many thanks for the functions.php temp fix and I'll watch for the next release.  Cheers!

**Comment by IlluminatePro** [comment]
Feature: it would be nice if the text field allowed HTML editing.  I find if inserted it's auto removed. (e.g. &nbsp).

**Comment by girishpanchal30** [comment]
@IlluminatePro If you would like to request a new feature, feel free to create a new ticket.
