### ISSUE TITLE
Critical error after activating the plugin

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/wp-maintenance-mode#315]
Hi there!

After activating the plugin and checking the website incognito, I got this critical error:
`An error of type E_ERROR was caused in line 89 of the file /home/u213785429/domains/stefancoti.com/public_html/root/wp-content/plugins/wp-maintenance-mode/includes/classes/wp-maintenance-mode.php. Error message: Uncaught Error: Call to a member function enqueue_google_fonts() on null in /home/u213785429/domains/stefancoti.com/public_html/root/wp-content/plugins/wp-maintenance-mode/includes/classes/wp-maintenance-mode.php:89 Stack trace: #0 /home/u213785429/domains/stefancoti.com/public_html/root/wp-includes/class-wp-hook.php(309): WP_Maintenance_Mode->{closure}(false) #1 /home/u213785429/domains/stefancoti.com/public_html/root/wp-includes/plugin.php(191): WP_Hook->apply_filters(false, Array) #2 /home/u213785429/domains/stefancoti.com/public_html/root/wp-includes/option.php(132): apply_filters('pre_option_page...', false, 'page_on_front', false) #3 /home/u213785429/domains/stefancoti.com/public_html/root/wp-includes/class-wp-query.php(1000): get_option('page_on_front') #4 /home/u213785429/domains/stefancoti.com/public_html/root/wp-includes/class-wp-query.php(1792): WP_Query->parse_query() #5 /home/u213785429/domains/stefancoti.com/public_html/root/wp-includes/class-wp-query.php(3586): WP_Query->get_posts() #6 /home/u2`

Here is what the website looks like:
<img width="1680" alt="Screenshot 2022-09-08 at 12 09 49" src="https://user-images.githubusercontent.com/86592992/189086429-ce23066a-92dc-4508-93d3-ea0c4d1c00e3.png">

If I deactivate WP Maintenance Mode, the website works again.
I can't replicate this issue on another instance.

**Comment by stefan-cotitosu** [comment]
https://root.stefancoti.com/wp-admin
radacina
Admin123

**Comment by selul** [comment]
@stefan-cotitosu @AndreeaCristinaRadacina please copy the health info and paste it here https://pastebin.com/

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina Can you make sure you were using latest version of Otter?

**Comment by AndreeaCristinaRadacina** [comment]
@HardeepAsrani yes, all plugins are updated to the last version

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina Was it a new website or somewhere where you had tried some previous dev version of WP Maintenance Mode before it was released?

**Comment by stefan-cotitosu** [comment]
It wasn't a new website. Site Health info should be available here

https://pastebin.com/PAYxdbib

**Comment by HardeepAsrani** [comment]
@AndreeaCristinaRadacina @stefan-cotitosu Can you reproduce the error again on that website and share the creds with me, if possible?

**Comment by HardeepAsrani** [comment]
Thank you both; we were able to find out what was causing it. PR incoming.

**Comment by AndreeaCristinaRadacina** [comment]
great! glad we could help!

**Comment by HardeepAsrani** [comment]
It should be fixed now; thank you @AndreeaCristinaRadacina & @stefan-cotitosu for your help! Let me know if you face this again!
