### ISSUE TITLE
Subscriber form not registering subscriber[in v2.5.1]

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/wp-maintenance-mode#323]
### Description:
Hey, a user reported that Subscribe form is not registering the subscriber data which can be found in WP- Maintenance Mode Settings > Modules. On this page, you can observe that the subscribe stats is still 0. A similar issue has been reported in the past https://github.com/Codeinwp/wp-maintenance-mode/issues/303

I myself have tried replicating this issue and this happens for me too. I have set up the SMTP  server and My subscribe form is working fine i.e I am able to receive the emails in my Gmail but when I went to check the subscribe stats it still shows 0. I downgraded the plugin version to 2.4.7 and on that version subscribe form stats are working fine i.e they are showing the correct No. and also we can access them as CSV files. So the issue that I am able to identify is that the new templates that are being created by the otter plugin are not linked correctly to the wp maintenance plugin that's why even after multiple subscribe form entries it still shows 0.

### How to reproduce:

1. Install the plugin and set up an SMTP server (I have added a tutorial link below) so that the form on the Maintenance mode template can work correctly.
2. After setting up the server, activate the Maintenance mode and use the coming soon template which has the subscribe form.
3. Open the page in a new tab where you are not logged in (go incognito). 
4. Enter some entries in the form.
5. Check it, You will receive the entries in your mail. 
6. Go to Settings> Modules. 
7. Observe the stats, you will see it's still 0.
8. Now roll back to version (2.4.7) which doesn't need the otter plugin for subscribe form.
9. Activate maintenance mode and enable the **show subscribe** option and do a form entry again.
10. Come back to the same settings page and observe that the subscribe stats are increased to 1. 

### Expected behavior:
The stats should increase with each form entry and form entries should be accessible through Wp maintenance settings as a CSV file like the previous version.
### Current behavior:
The subscribe stats are stuck at 0.
### Reference:
The form :
![image](https://user-images.githubusercontent.com/110405452/192272896-1d9523d3-4f2a-486c-8726-180b94275a51.png)

Plugin settings showing subscribe stats 0 (v2.5.1):
![image](https://user-images.githubusercontent.com/110405452/192272718-5a1b7545-2364-4ef2-b1c1-14032f1a5ed0.png)

Plugin settings before form entry (v2.4.7):
![image](https://user-images.githubusercontent.com/110405452/192272369-4066bcb6-65ea-4d1b-ab18-b0493196d56a.png)

Plugin settings showings stats after form entry(v2.4.7):
![image](https://user-images.githubusercontent.com/110405452/192272532-bf196e61-7079-4511-ab0f-391a051f8ffc.png)

Screencast of the issue on the new version: https://www.loom.com/share/b307c82c1e4d4e2185898a50357243fb

The SMTP guide: https://docs.themeisle.com/article/1713-how-to-set-up-your-smtp-server
The ticket on HS: https://secure.helpscout.net/conversation/2016995137/337902?folderId=931544

### Technical info
* WordPress version: 6.0.2
* Plugin version: 2.5.1

**Comment by girishpanchal30** [comment]
Hey @kushh23

Fixed save subscriber entry issue. Please check with this PR https://github.com/Codeinwp/wp-maintenance-mode/pull/326

Thanks

**Comment by kushh23** [comment]
Hey @girishpanchal30,

I checked the new build in the PR and it fixed this issue.🙌

Thanks
