### ISSUE TITLE
Adding Landing pages to the Template Library

### ISSUE THREAD

**Issue by JohnPixle** [Codeinwp/wp-maintenance-mode#327]
As discussed [in Slack](https://vertistudio.slack.com/archives/C02JC68P404/p1664191646111599?thread_ts=1663579666.320889&cid=C02JC68P404), we are going to add landing pages to the template library of the plugin.

Initially, we are going to introduce a generic `Landing page` category where we will include templates from different niches/subcategories. 

Below is a screenshot from the [Figma file](https://www.figma.com/file/r1pLMeeq4nhynBlCKY6mOQ/Coming-Soon-pages?node-id=509%3A1126) where I have been working on some mockups for these templates.

### Templates
Currently the collection will include:

- A personal / bio landing page
- A simple portfolio
- A Linktree-type page
- A wedding announcement page
- A service landing page
- An Event landing page

- One more Coming Soon page
- One more Maintenance page

I will be building the landing pages in the demo site, You should be able to find them [in this page.](https://demosites.io/otter/landing-pages/)

![landing pages](https://user-images.githubusercontent.com/4193672/192504661-cbb0947c-54dd-4ef5-a836-67696d7416a2.png)

### Monitoring user preferences through API
As Marius mentioned in Slack, 

> would be super great if we can send the page type selected, both the name and the category on the api when they subscribe with email. in this way we can monitor which category/page they like more.

### Changes in the Wizard

We need to update the Wizard flow, and include a Landing Page option.

### Review for potential changes in the Plugin Settings

We also need to review the current settings and see if we need to make any changes there. Some things we need to do are:

- [x] Include the new templates in the library (design tab)
- [x] Add the Landing page category in the dropdown (design tab)
- [x] Review main settings page and see if we need to make any meaningful changes here, in case the user has selected a Landing page. 

### Next Steps

From my side, I will start building the templates, and -in parallel- work on the Wizard tweaks in order for @arinaturcu to be able to work on it while I complete the design of all templates.

Keeping you in the loop @selul @HardeepAsrani @arinaturcu @mghenciu 

Please let me know your input, suggestions or questions.

**Comment by JohnPixle** [comment]
Hey @arinaturcu Just to add a couple of things at the settings side, perhaps you might consider working on these while I finalise the templates part. Here is a quick video outlining them for better clarity: https://www.loom.com/share/337e936205924359b101ba1978611a3f

- [ ] Include `Landing Page` Type in the wizard. [Figma in Progress](https://www.figma.com/file/r1pLMeeq4nhynBlCKY6mOQ/Coming-Soon-pages?node-id=534%3A753).

- [ ] Include `Landing Page` Type in the dropdown at Design tab. Of course we will add the new templates as well in the library.

- [ ] Under the Select Page dropdown, I think it would be a good idea to rephrase the description now that we have more than 2 page types. How about this: _Select the page that will be used as the Maintenance, Coming Soon or Landing page_ 

![Screenshot 2022-09-30 at 13 44 06](https://user-images.githubusercontent.com/4193672/193253958-e92b1e29-5441-4eab-b4ee-e90962240056.png)


- [ ] Let's right-align the dropdown that filters the template types

![Screenshot 2022-09-30 at 13 49 02](https://user-images.githubusercontent.com/4193672/193254328-23e1bdfd-9227-4df5-b937-f62b18ac82c3.png)

- [ ] There is a small typo in the description above the templates. It reads _**This** templates..._ but it should be _**These** templates..._

- [ ] Under Settings \ Modules we have a subscribe section, which I don't think is needed anymore. Perhaps we should remove this? Additionally, if we decide to remove that part maybe we should rename the whole tab into Analytics (since only the analytics will be there)?

![Screenshot 2022-09-30 at 12 59 15](https://user-images.githubusercontent.com/4193672/193248540-8eef4763-62d8-481d-b296-2dd22b0c3d57.png)

- [ ] Finally, as a note to self, we should update the template screenshots, as I have done some very minor tweaks on the existing templates (based on some recent improvements on the Otter Form Block). I'll take care of that.

Feel free to ping me for any questions, clarifications or anything I can help with. I will give you a heads-up for when the template work in done so you can copy the code.

Thanks!

Keeping @mghenciu and @selul in the loop ✌🏻

**Comment by JohnPixle** [comment]
As a quick update I have completed the "default" landing page that is going to be visible in the wizard, hoping to have some visual consistency in the three thumbnails.

Having some 

Template is here: https://demosites.io/otter/landing-pages/default-landing-page/

![Screenshot 2022-10-03 at 12 42 49](https://user-images.githubusercontent.com/4193672/193547938-8e66f6f0-fae3-435a-88ce-806e9b991af7.png)


Apart for a final check and some micro-tweaks I plan to do at some of the landing pages, This is mainly ready for implementation!

**Comment by JohnPixle** [comment]
@arinaturcu Just a heads-up that I am completely done from the design aspect of things, so based on the priority feel free to proceed with this whenever you see fit, and let me know if I can be of any help ✌🏻 

Keeping @HardeepAsrani and @selul in the loop

Thanks!

**Comment by HardeepAsrani** [comment]
@arinaturcu The workflow won't be the same. We don't need to save the ID of the Landing Page. @JohnPixle

**Comment by JohnPixle** [comment]
I am not sure what the approach would be here @HardeepAsrani, I just posted a question for Marius [in Slack.](https://vertistudio.slack.com/archives/C02JC68P404/p1665498944045519)

**Comment by arinaturcu** [comment]
> - [ ] Under Settings \ Modules we have a subscribe section, which I don't think is needed anymore. Perhaps we should remove this? Additionally, if we decide to remove that part maybe we should rename the whole tab into Analytics (since only the analytics will be there)?

We need this since the subscribers from the bot will be there.

**Comment by JohnPixle** [comment]
_> We need this since the subscribers from the bot will be there._
Good catch, makes sense 👍🏻
