### ISSUE TITLE
The latest version v2.5.2 broked site of many users

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/wp-maintenance-mode#330]
Hey, Multiple users are reporting that the new version (v2.5.2) has broken their site in one way or another. Some of them are facing login issues and some of them are facing menu missing on their website ( even my instance has the same problem)
 ### Reference-
[wp.org forum](https://wordpress.org/support/plugin/wp-maintenance-mode/)

### Technical info-
WordPress version : 6.0.2
Plugin version: 2.5.2

**Comment by gammesB** [comment]
This was also a problem for us. The annoying part was that the error(after enabling debug) we got didn't have anything about the plugin mentioned.
<img width="948" alt="Screenshot_3" src="https://user-images.githubusercontent.com/96754537/192651362-f8ede72b-333c-4ab3-8d7b-0d0f0a9aeef8.png">
I am confused how this could get released without it being noticed.
This at least learned us a valuable lesson. don't keep auto update enabled on plugins.

We are also on the latest wordpress(6.0.2) and on php 7.4 as recommended by wordpress.

**Comment by selul** [comment]
Hi there,

I’m really sorry for the issues caused; it was a small oversight affecting the post types with no templates.

I’ve rolled out a fix in v2.5.3, and everything should be fine now.

Thank you for understanding.
