### ISSUE TITLE
Some Custom Archive Page Used with wpmm-page-template.php 

### ISSUE THREAD

**Issue by ken-kurihara** [Codeinwp/wp-maintenance-mode#331]
as far as i know, its been okay till 2.5.1.
but not anymore after i updated to 2.5.2, when some custome post-type archive page are used with wpmm-page-template.php beyond the priority order of template hierarchy.
would anybody have any idea how i can check or fix it?
thanks in advance.

**Comment by selul** [comment]
Hi there,

I’m really sorry for the issues caused; it was a small oversight affecting the post types with no templates.

I’ve rolled out a fix in v2.5.3, and everything should be fine now.

Thank you for understanding.
