### ISSUE TITLE
WP Maintenance Mode deactivation

### ISSUE THREAD

**Issue by delcruft** [Codeinwp/wp-maintenance-mode#355]
Hi,

I've been using this for sometime without issue. However since the most recent update (2.6.2) I've experienced an issue with deactivating. In particular, I downloaded one of the templates for the maintenance page (maintenance 2). When maintenance mode is deactivated under the general menu and I log out I still couldn't view the site. It just displayed the maintenance page template. After further investigation, I realised that actually any page that I previous tried to view in maintenance mode continues to display the template screen those that I had not displayed as expected. I've cleared browsing data, emptied caches, tried a browser in private mode and emptied the cache on our server. None of these have resolved the issue.

What's going on?

**Comment by selul** [comment]
hi there, 

I tried to reproduce this behavior, but I'm unable to. I spun up a new InstaWP site, installed the plugin, and followed your steps and the deactivation works fine. 

Would help if you can provide a place where we can see the issue either via instawp.io or your testing site. 

I'm looking forward to your reply.

**Comment by delcruft** [comment]
Thank you for your reply. I wonder if it's simply a caching issue. I deleted the maintenance page template, cleared the browser cache, server cache and WordPress cache. A few hours later it resolved it.
