### ISSUE TITLE
Add the update page & include the sdk

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/wp-maintenance-mode#386]
### What problem does this address?

@vytisbulkevicius the new SDK is out, since this is our biggest product, it would be great if we can update the SDK & release it. There would be no upgrade page or extra pages.

### What is your proposed solution?

_Edit from Hardeep:_ We can move the settings from Options to a top-level admin menu and make sure every reference to it in code and links are migrated safely + integrate About page from SDK.

**Comment by vytisbulkevicius** [comment]
@ineagu, so we don't want to have the "about us" page integrated for this plugin?
Then we don't need to add the code change but I want to be sure that this is what you meant with no extra pages.

**Comment by ineagu** [comment]
@vytisbulkevicius in the original spec, there is an optional argument for the function to add more tabs linking to some other pages. My message was that we should add just the about us page, without the optional tabs configured.

**Comment by HardeepAsrani** [comment]
I'll pause the release https://github.com/Codeinwp/wp-maintenance-mode/pull/388 her for this, @ineagu just to confirm one thing, right now WPMM doesn't add any top-level menu page. This mean we need to add a top-level menu page for this plugin to add the About page, right?

**Comment by ineagu** [comment]
@HardeepAsrani you are right, for me, I don't see any problem with creating a top-level menu setting, that can create more flexibility in the future.

If you see any UX issue, we can skip it too. As of now, I don't have any data on how much the About page helps, so is hard to judge, if not a major concern we can create the top-level setting and go with it & later evaluate.

Do you want me to create a dedicated issue for that?

**Comment by HardeepAsrani** [comment]
@ineagu No, this should do. We can just have a simple top-level menu with two pages, Settings that will have the existing plugin settings + About Us page added via SDK.
