### ISSUE TITLE
Templates page look unusable on tastewp

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/wp-maintenance-mode#390]
### Description

Tried to take a look at Lightstart and here is what the templates page looks like: https://vertis.d.pr/i/J8kOhu.

### Step-by-step reproduction instructions

1. Go to the design tab
2. https://vertis.d.pr/i/J8kOhu

### Environment info

https://pastebin.com/crkpgiFf

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
This happens using **Safari** browser, it looks fine with Chrome or Firefox.

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the issue is fixed now 👍
