### ISSUE TITLE
Fatal error when using WP 4.6

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/wp-maintenance-mode#402]
### Description

When i use the plugin with WordPress 4.6, there will be a fatal error in the site https://vertis.d.pr/i/dKDZ8O

On wp.org the min version is [3.5](https://vertis.d.pr/i/PVCtnX) so i think we should raise it to 4.7, where everything is working well

### Step-by-step reproduction instructions

1. Install Lightstart
2. Change the WordPress version to 4.6
3. Check if there is any fatal error

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/i/dKDZ8O

### Environment info

WordPress 4.6 / PHP 7.0 / Lightstart 2.6.8

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
Updated. Thanks!
