### ISSUE TITLE
Conflict with WP-Optimize

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/wp-maintenance-mode#404]
### Description

A user reported that a fatal error occurs when Wp-Optimize and Lightstart are activated and you setup a coming soon/maintenance page. The issue appears when creating the page from the setup wizard, as well as when it is created later on, from LightStart -> Design. It lets you select the desired template for the page from the predesigned ones, but after the last step, when you can choose to go to the page or to go to the settings, the fatal error occurs. I am able to replicate the issue on my instance.

### Step-by-step reproduction instructions

1. Install WP-Optimize
2. Install LightStart
3. Go through the setup wizard and create a page
4. Check the error after the last step of the wizard

### Screenshots, screen recording, code snippet or Help Scout ticket

![Capture](https://github.com/Codeinwp/wp-maintenance-mode/assets/86592341/62bf533b-f5af-40ce-acbb-0cb332b80743)

Reported [here](https://wordpress.org/support/topic/conflict-with-wp-optimize-5/)

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I reviewed this issue and found that it happens when we set the `private` status instead of `publish`

@HardeepAsrani @arinaturcu Can you please review my changes? It might generate a regression issue.

Thanks
