### ISSUE TITLE
Conflict with Elementor

### ISSUE THREAD

**Issue by Mara42** [Codeinwp/wp-maintenance-mode#441]
### Description

When the plugin is installed and configured, it causes issues with the Elementor editor. Users attempting to edit pages find that the editor appears to load indefinitely and only allows access in safe mode. When entering safe mode, a broken version of the page is displayed, which differs significantly from the intended design. This problem occurs only if the page is imported right after installing the plugin when that menu appears and lets you choose the template you want. 

### Step-by-step reproduction instructions

Note: It doesn’t matter if you have Elementor already installed or if you install it after LightStart as long as you follow all the steps
1. Install LightStart
2. From the menu that appears right after Installing and Activating it choose a template and click Continue
3. Click on View Page
4. Make sure you have Elementor installed
5. Click Edit with Elementor on the page just imported with LightStart

### Screenshots, screen recording, code snippet or Help Scout ticket

Thread on forum: https://wordpress.org/support/topic/elementor-crash-with-lightstart/

This is how the page appears if you enable safe mode when replicating the issue: 
<img width="1670" alt="Screenshot 2024-08-06 at 15 37 17" src="https://github.com/user-attachments/assets/7fdcf003-d5a0-4083-a99e-b5315ef0b20a">

This is how the page should actually look like:
<img width="1680" alt="Screenshot 2024-08-06 at 15 37 27" src="https://github.com/user-attachments/assets/3cb303e0-5270-49ed-bdf6-d148aeb03811">

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
I've reviewed this issue and fixed it here - https://github.com/Codeinwp/wp-maintenance-mode/pull/442

**Comment by Mara42** [comment]
I have tested along with @AndreeaCristinaRadacina, everything works perfectly now. 
<img width="2205" alt="Screenshot 2024-08-09 at 13 44 31" src="https://github.com/user-attachments/assets/8aa33bee-7b40-4727-921c-7bdcbbb5e6f8">
