### ISSUE TITLE
Conflict with WPForms in Dashboard style and layout

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/wp-maintenance-mode#452]
### Description

With the latest version of WPForms and Lighstart, there are some layout and style conflicts issues in the Dashboard.

It seems to work correctly with LightStart version 2.6.11. (two versions ago)

### Step-by-step reproduction instructions

1. Install and activate: LightStarts and WPForms.
2. Check the WPForms -> All Forms page with and without LIghtStart active
3. Create a form and check the page again: the button style is different, and some select of settings appears in the bottom right corner of the page

### Screenshots, screen recording, code snippet or Help Scout ticket

**When no form was created**

![Image](https://github.com/user-attachments/assets/825bdfee-3dfd-4c2a-9d31-a72fe6a04cc7)

**When at least one form was created**

![Image](https://github.com/user-attachments/assets/85453ddf-de4c-4159-88ec-f1b1cc174167)

### Environment info

https://pastebin.com/n7TtEFKd

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by girishpanchal30** [comment]
I've reviewed this issue and fixed it here - https://github.com/Codeinwp/wp-maintenance-mode/pull/455

**Comment by stefan-cotitosu** [comment]
It works properly with the mentioned PR.
