### ISSUE TITLE
Please add support for piwik

### ISSUE THREAD

**Issue by 2020media** [Codeinwp/wp-maintenance-mode#84]
We prefer to use Piwik [http://piwik.org/] over Google Analytics.

i tried to paste the Piwik script in your  Google Analytics box but in the resulting page, I did not find the code.
There is a piwik plugin for WP, however this relies on a couple of functions like footer being available.

**Comment by georgejipa** [comment]
Please give me that code because I want to test. Thanks.

**Comment by 2020media** [comment]
example of code



<script type="text/javascript">
  var _paq = _paq || [];
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="//analyticsurl/";
    _paq.push(['setTrackerUrl', u+'piwik.php']);
    _paq.push(['setSiteId', 99]);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

**Comment by controlcde** [comment]
**+1**

It would be fine if the "google analytics" section will be renamed into "analytics" and a dropdown box to select piwik or ga. Or only the complete tracking code should be insert.

**Comment by Reekdeb** [comment]
**+1**
We prefer to use piwik. Please enable support for piwik or any other custom tracking code.

**Comment by langhaarschneider** [comment]
+1
I would also like to use piwik

**Comment by PMK** [comment]
+1

If you put the Piwik code inside the Google Analytics textarea field, you'll get a PHP parse error.

```
[error] PHP Parse error:  syntax error, unexpected '_paq' (T_STRING), expecting ',' or ';' in /path/to/wp-content/plugins/wp-maintenance-mode/includes/classes/wp-maintenance-mode.php(44) : runtime-created function on line 7
```

I like to see a textarea field to put any JavaScript code for tracking.
